spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_items_rest?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Root




