spring:
  datasource:
    url: jdbc:mysql://localhost:3306/come_to_gyumri?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root


restaurantImages:
  upload:
    path: C:\\Users\\Hayk\\IdeaProjects\\ComeToGyumri\\restaurantImage\\

come_to_gyumri:
  upload:
    path: C://Users//Mkhitar Mkhitaryan//Desktop//img//
hotelImagePath:
  upload:
    path: C:\\hotelImagePath\\

server:
  port: 8080


